In [219]:
import numpy as np
# exercise 1
array = np.array([1,5,6,8,4,7,8,2,3,6,9,14,4,7,8,5])
print(np.where((array<8) & (array>3),-array,array))

# exercise 2
array[np.argmax(array)]=0
print(array)

# exercise 3
array = np.array([[1, 2, 3], [4, 5, 6, 8, 7]])
print(array[1])
array_repeats0 = np.repeat(array[0], np.size(array[1])).reshape((np.size(array[0]) * np.size(array[1]), 1))
array_repeats1 = np.transpose(
    np.repeat(array[1], np.size(array[0])).reshape((np.size(array[1]), np.size(array[0])))).reshape(
    [np.size(array[0]) * np.size(array[1]), 1])
result = np.append(array_repeats0, array_repeats1, axis=1)
print(result)

# exercise 4

# A = np.random.randint(4,size=24).reshape([8,3])
# print(A)
# B = np.random.randint(4,size=4).reshape([2,2])
# unique = np.unique(B)
# print(unique)
# print('\n')
# if np.size(unique)==3:
#   print(np.where((unique==np.sort(A)).all(axis=1)))


# exercise 5

A = np.random.randint(2,size = 30).reshape([10,3])

print(A)
print('Unique A')
for row in A:
  if np.size(np.unique(row))>1:
    print(row)


# exercise 6
print('\n')
print(A)
rows, columns = A.shape
for i in range(rows):
    for j in range(i + 1, rows):
        if (A[i] == A[j]).all():
            A = np.delete(A, i, axis=0)
            rows = rows - 1
            break;
print(A)




[ 1 -5 -6  8 -4 -7  8  2  3 -6  9 14 -4 -7  8 -5]
[1 5 6 8 4 7 8 2 3 6 9 0 4 7 8 5]
[4, 5, 6, 8, 7]
[[1 4]
 [1 5]
 [1 6]
 [1 8]
 [1 7]
 [2 4]
 [2 5]
 [2 6]
 [2 8]
 [2 7]
 [3 4]
 [3 5]
 [3 6]
 [3 8]
 [3 7]]
[[1 1 1]
 [1 0 0]
 [0 0 0]
 [0 1 0]
 [1 0 1]
 [0 1 1]
 [0 0 0]
 [1 1 1]
 [1 1 0]
 [1 0 0]]
Unique A
[1 0 0]
[0 1 0]
[1 0 1]
[0 1 1]
[1 1 0]
[1 0 0]


[[1 1 1]
 [1 0 0]
 [0 0 0]
 [0 1 0]
 [1 0 1]
 [0 1 1]
 [0 0 0]
 [1 1 1]
 [1 1 0]
 [1 0 0]]
[[1 0 0]
 [0 1 0]
 [1 0 1]
 [0 1 1]
 [0 0 0]
 [1 1 1]
 [1 1 0]
 [1 0 0]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:11: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  # This is added back by InteractiveShellApp.init_path()


In [226]:
# task 1 
import numpy as np

X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])
X_ = [[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]
# python
min_ = min(len(X_),len(X_[0]))
x=1
for i in range(min_):
  if X_[i][i]!=0:
    x= x*X_[i][i]
print(x)
# numpy
np.prod(np.diag(X)[np.diag(X)!=0])


3
3


3

In [231]:
# task 2
import numpy as np
x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2])
# numpy
print((np.sort(x)==np.sort(y)).all())
# python 
x = [1, 2, 2, 4]
y = [4, 2, 1, 2]
x.sort()
y.sort()
for i in range(len(x)):
  if x[i] != y[i]:
    print(False)
    break;
print(True)

True
True


In [259]:
# task 3
import numpy as np

# numpy
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
x_nonzero = np.array(np.where(x == 0)) + 1
x_nonzero = x_nonzero[0]
x_nonzero = x_nonzero[x_nonzero!=np.size(x)]
print(np.max(np.take(x,x_nonzero)))

# python
x = [6, 2, 0, 3, 0, 0, 5, 7, 0]
x_nonzero = []
for i in range(len(x)):
  if x[i]==0:
    if i!= len(x)-1:
      x_nonzero.append(x[i+1])
print(max(x_nonzero))

5
5


In [268]:
# task 4 
import numpy as np
from collections import Counter
# numpy
x = np.array([2, 2, 2, 3, 3, 3, 5])
print(np.unique(x, return_counts=True))

# python 
x = [2, 2, 2, 3, 3, 3, 5]
c = Counter(x)
print(c)

(array([2, 3, 5]), array([3, 3, 1]))
Counter({2: 3, 3: 3, 5: 1})


In [ ]:
# task 5
import numpy as np



In [287]:
# task 6

import numpy as np

calorie_stats = np.loadtxt("/content/cereal.csv", delimiter=",")
calorie_stats 

average_calories = np.mean(calorie_stats-60)
print(average_calories)
calorie__stats_sorted = np.sort(calorie_stats)
calorie__stats_sorted
median_calories = np.mean(calorie__stats_sorted)
print(median_calories)
nth_percentile= np.percentile(calorie_stats,4)
more_calories = np.size(calorie_stats[calorie_stats>60])/np.size(calorie_stats)
print(more_calories)
calorie_std  = np.std(calorie_stats)
print(calorie_std)

46.883116883116884
106.88311688311688
0.961038961038961
19.35718533390827


# Новый раздел